name: bangla
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2021.5.30=py38h578d9bd_0
  - curl=7.71.1=hbc83047_1
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.4=h7ca028e_0
  - glib=2.68.2=h36276a3_0
  - icu=58.2=hf484d3e_1000
  - jpeg=9d=h36c2ea0_0
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=he1b5a44_3
  - ncurses=6.2=he6710b0_1
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.44=he1b5a44_0
  - pip=21.0.1=py38h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.90.1=h4190859_0
  - poppler-data=0.4.10=0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.5=h7579374_1
  - python_abi=3.8=1_cp38
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.3
    - bleach==3.3.0
    - bs4==0.0.1
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==8.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - easyocr==1.3.2
    - efficientnet==1.0.0
    - entrypoints==0.3
    - flatbuffers==1.12
    - fonttools==4.22.1
    - gast==0.3.3
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - image-classifiers==1.0.0
    - imageio==2.9.0
    - ipykernel==5.5.3
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - jupyterthemes==0.20.0
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lesscpy==0.14.0
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - nltk==3.6.2
    - notebook==6.3.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pdf2image==1.15.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - ply==3.11
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - protobuf==3.15.8
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.8.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytesseract==0.3.7
    - python-bidi==0.4.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - segmentation-models==1.0.1
    - send2trash==1.5.0
    - six==1.15.0
    - soupsieve==2.2.1
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - terminado==0.9.4
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.6.6
    - torch==1.8.1
    - torchvision==0.9.1
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wand==0.6.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xlrd==1.2.0
prefix: /home/ansary/anaconda3/envs/bangla
